/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obatbaru;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class obatbaruu extends javax.swing.JFrame {
    private String[] namaobat;
    private String[] deskripsiobat;
    
    public obatbaruu() {
    initComponents();
    
    namaobat = new String[]{"Laserin", "Decadryl", "Dicom", "Procold Flu","Symbicorts",
                            "FintolirInhaler", "Bodrex", "Kelohrida", "Paracemtamol", "Sumasgetic"};
    deskripsiobat = new String[]{
                "Laserin membantu meredakan batuk dan melegakan tenggorokan", //0
                "untuk mengurangi nyeri, peradangan, dan demam", //1
                " obat pilek hidung tersumbat yang memiliki kandungan Pseudoephedrine dan Triprolidine HCl", //2
                "meringankan gejala flu seperti demam, sakit kepala", //3
                "Obat ini digunakan untuk terapi asma dan PPOK (Penyakit Paru Obstruktif Kronik) berat", //4
                "inhaler adalah obat model semprot untuk mengatasi gejala asma.", //5
                " meringankan sakit kepala, dan menurunkan demam. Meringankan sakit kepala", //6
                "Mengatasi flu dan batuk yang disertai batuk berdahak", //7
                "penurun demam dan pereda nyeri seperti sakit kepala , sakit gigi dan nyeri ringan.", //8
                "Mengatasi flu, ex: demam, sakit kepala, hidung tersumbat" //9
        };
    }

 private void tampilkanObat(String gejala, String[] namaObat, String[] deskripsiObat) {
        switch (gejala) {
            case "BATUK":
                Namaobat.setText("Namaobat : " + namaObat[0] +" dan " + namaObat[1]);
                Deskripsi.setText("Deskripsiobat : " + deskripsiObat[0] + " dan " + deskripsiObat[1]);
                break;
            case "PILEK":
                Namaobat.setText("Namaobat : " + namaObat[2] + " dan " + namaObat[3]);
                Deskripsi.setText("Deskripsobat : " + deskripsiObat[2] + " dan " + deskripsiObat[3]);
                break;
            case "SESAK NAFAS":
                Namaobat.setText("Namaobat : " + namaObat[4] + " dan " + namaObat[5]);
                Deskripsi.setText("Deskripsiobat : " + deskripsiObat[4] + " dan " + deskripsiObat[5]);
                break;
            case "PUSING":
                Namaobat.setText("Namaobat : " + namaObat[6] + " dan " + namaObat[7]);
                Deskripsi.setText("Deskripsiobat : " + deskripsiObat[6] + " dan " + deskripsiObat[7]);
                break;
            case "SAKIT GIGI":
                Namaobat.setText("Namaobat : " + namaObat[8] + " dan " + namaObat[9]);
                Deskripsi.setText("Deskripsiobat : " + deskripsiObat[8] + " dan " + deskripsiObat[9]);
                break;
            default:
                Namaobat.setText("Nama Obat:... ");
                Deskripsi.setText("Deskripsi:... ");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ATAS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        batuk = new javax.swing.JButton();
        pilek = new javax.swing.JButton();
        sesaknafas = new javax.swing.JButton();
        pusing = new javax.swing.JButton();
        sakitgigi = new javax.swing.JButton();
        BAWAH = new javax.swing.JPanel();
        Deskripsi = new javax.swing.JLabel();
        Namaobat = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TENGAH = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ATAS.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELAMAT DATANG DI TOKO APOTIK HERBAL");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel2.setText("KETERANGAN/DESKRIPSI OBAT");
        jPanel1.add(jLabel2);

        batuk.setText("BATUK");
        batuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batukActionPerformed(evt);
            }
        });
        jPanel1.add(batuk);

        pilek.setText("PILEK");
        pilek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilekActionPerformed(evt);
            }
        });
        jPanel1.add(pilek);

        sesaknafas.setText("SESAK NAFAS");
        sesaknafas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesaknafasActionPerformed(evt);
            }
        });
        jPanel1.add(sesaknafas);

        pusing.setText("PUSING");
        pusing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pusingActionPerformed(evt);
            }
        });
        jPanel1.add(pusing);

        sakitgigi.setText("SAKIT GIGI");
        sakitgigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sakitgigiActionPerformed(evt);
            }
        });
        jPanel1.add(sakitgigi);

        javax.swing.GroupLayout ATASLayout = new javax.swing.GroupLayout(ATAS);
        ATAS.setLayout(ATASLayout);
        ATASLayout.setHorizontalGroup(
            ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ATASLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(148, 148, 148))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        ATASLayout.setVerticalGroup(
            ATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ATASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(ATAS, java.awt.BorderLayout.PAGE_START);

        BAWAH.setLayout(new java.awt.GridBagLayout());

        Deskripsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Deskripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Deskripsi.setText("DESKRIPSI OBAT =");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        BAWAH.add(Deskripsi, gridBagConstraints);

        Namaobat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Namaobat.setText("NAMA OBAT =");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        BAWAH.add(Namaobat, gridBagConstraints);

        jLabel18.setText("____________________________________________________________________________________________________________________________________________");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        BAWAH.add(jLabel18, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        BAWAH.add(jButton1, gridBagConstraints);

        getContentPane().add(BAWAH, java.awt.BorderLayout.PAGE_END);

        TENGAH.setBackground(new java.awt.Color(102, 102, 102));
        TENGAH.setLayout(new java.awt.GridLayout(4, 3, 9, 9));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/BATUK.jpeg"))); // NOI18N
        jLabel6.setText("LASERIN");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel6.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 50));
        TENGAH.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/BATUK2.jpeg"))); // NOI18N
        jLabel7.setText("DECADRYL");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        TENGAH.add(jLabel7);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/PILEK 2.jpeg"))); // NOI18N
        jLabel5.setText("DICOM");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        TENGAH.add(jLabel5);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/PILEK.jpeg"))); // NOI18N
        jLabel9.setText("PROCOLD FLU");
        TENGAH.add(jLabel9);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/SESAK NAFAS.jpeg"))); // NOI18N
        jLabel8.setText("SY8MBICORT");
        TENGAH.add(jLabel8);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/SESAK NAFAS 2.jpeg"))); // NOI18N
        jLabel10.setText("VENTOLIN INHALER");
        TENGAH.add(jLabel10);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/PUSING.jpeg"))); // NOI18N
        jLabel13.setText("BODREX");
        TENGAH.add(jLabel13);

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/PUSING 1.jpeg"))); // NOI18N
        jLabel11.setText("KELOHRIDA");
        TENGAH.add(jLabel11);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/SAKIT GIGI.jpeg"))); // NOI18N
        jLabel12.setText("PARACETAMOL");
        TENGAH.add(jLabel12);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obatbaru/SAKIT GIGI 2.jpeg"))); // NOI18N
        jLabel4.setText("SUMAGESTIC");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 100));
        TENGAH.add(jLabel4);

        getContentPane().add(TENGAH, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batukActionPerformed
     tampilkanObat("BATUK", namaobat, deskripsiobat);
    }//GEN-LAST:event_batukActionPerformed

    private void pilekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilekActionPerformed
     tampilkanObat("PILEK", namaobat, deskripsiobat);
    }//GEN-LAST:event_pilekActionPerformed

    private void sesaknafasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesaknafasActionPerformed
     tampilkanObat("SESAK NAFAS", namaobat, deskripsiobat);
    }//GEN-LAST:event_sesaknafasActionPerformed

    private void pusingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pusingActionPerformed
     tampilkanObat("PUSING", namaobat, deskripsiobat);
    }//GEN-LAST:event_pusingActionPerformed

    private void sakitgigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sakitgigiActionPerformed
     tampilkanObat("SAKIT GIGI", namaobat, deskripsiobat);
    }//GEN-LAST:event_sakitgigiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JOptionPane.showMessageDialog(this, 
            "TERIMAKASIH SUDAH BELI", 
            "Peringatan", 
            JOptionPane.WARNING_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(obatbaruu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(obatbaruu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(obatbaruu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(obatbaruu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new obatbaruu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ATAS;
    private javax.swing.JPanel BAWAH;
    private javax.swing.JLabel Deskripsi;
    private javax.swing.JLabel Namaobat;
    private javax.swing.JPanel TENGAH;
    private javax.swing.JButton batuk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pilek;
    private javax.swing.JButton pusing;
    private javax.swing.JButton sakitgigi;
    private javax.swing.JButton sesaknafas;
    // End of variables declaration//GEN-END:variables
}
