/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktpmvs3;

import javax.swing.JOptionPane;

/**
 *
 * @author rival
 */
public class apotek extends javax.swing.JFrame {

    /**
     * Creates new form apotek
     */
    public apotek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        daftarobat = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        Gejala = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        detailobat = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Bayar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        daftarobat.setBackground(new java.awt.Color(255, 255, 204));
        daftarobat.setLayout(new java.awt.GridLayout(11, 5, 4, 5));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Nama Obat");
        daftarobat.add(jLabel22);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Gambar Obat");
        daftarobat.add(jLabel23);

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox1.setText("Analgestik");
        daftarobat.add(jCheckBox1);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat1-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel2);

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox2.setText("Antasida");
        daftarobat.add(jCheckBox2);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat2-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel3);

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox3.setText("Anticemas");
        daftarobat.add(jCheckBox3);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat3-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel4);

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox4.setText("Bodrex");
        daftarobat.add(jCheckBox4);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat4-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel5);

        buttonGroup1.add(jCheckBox5);
        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox5.setText("Antibiotik");
        daftarobat.add(jCheckBox5);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat5-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel6);

        buttonGroup1.add(jCheckBox6);
        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox6.setText("Antikonvulsan");
        daftarobat.add(jCheckBox6);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat6-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel7);

        buttonGroup1.add(jCheckBox7);
        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox7.setText("Paramex");
        daftarobat.add(jCheckBox7);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat7-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel9);

        buttonGroup1.add(jCheckBox8);
        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox8.setText("Paracetamol");
        daftarobat.add(jCheckBox8);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat8-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel10);

        buttonGroup1.add(jCheckBox9);
        jCheckBox9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox9.setText("Mixagrip");
        daftarobat.add(jCheckBox9);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat9-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel8);

        buttonGroup1.add(jCheckBox10);
        jCheckBox10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox10.setText("Oskadon");
        daftarobat.add(jCheckBox10);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\rival\\Downloads\\iloveimg-resized\\obat10-removebg-preview.png")); // NOI18N
        daftarobat.add(jLabel11);

        getContentPane().add(daftarobat, java.awt.BorderLayout.CENTER);

        Gejala.setBackground(new java.awt.Color(102, 102, 102));
        Gejala.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Apotak Telang Madura Utm");
        Gejala.add(jLabel1, new java.awt.GridBagConstraints());

        getContentPane().add(Gejala, java.awt.BorderLayout.PAGE_START);

        detailobat.setBackground(new java.awt.Color(255, 255, 204));
        detailobat.setLayout(new java.awt.GridLayout(11, 0, 0, 10));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Deskripsi");
        detailobat.add(jLabel24);

        jLabel12.setBackground(new java.awt.Color(0, 255, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("meredakan nyeri");
        detailobat.add(jLabel12);

        jLabel13.setBackground(new java.awt.Color(0, 255, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("gangguan pencernaan dan gejala mulas");
        detailobat.add(jLabel13);

        jLabel14.setBackground(new java.awt.Color(0, 255, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText(" bersifat sedatif (menenangkan)");
        detailobat.add(jLabel14);

        jLabel15.setBackground(new java.awt.Color(0, 255, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Pusing di kepala");
        detailobat.add(jLabel15);

        jLabel16.setBackground(new java.awt.Color(0, 255, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("melawan infeksi bakteri");
        detailobat.add(jLabel16);

        jLabel17.setBackground(new java.awt.Color(0, 255, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("mencegah kejang atau serangan epilepsi");
        detailobat.add(jLabel17);

        jLabel18.setBackground(new java.awt.Color(0, 255, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Untuk kepala sakit bagian tertentu");
        detailobat.add(jLabel18);

        jLabel19.setBackground(new java.awt.Color(0, 255, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("meredakan rasa nyeri dan menurunkan demam");
        detailobat.add(jLabel19);

        jLabel21.setBackground(new java.awt.Color(0, 255, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Fluu");
        detailobat.add(jLabel21);

        jLabel20.setBackground(new java.awt.Color(0, 255, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Nyeri pada badan");
        detailobat.add(jLabel20);

        getContentPane().add(detailobat, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String obatDipilih = "Obat yang Anda beli: \n";

        if (jCheckBox1.isSelected()) {
           obatDipilih += "Analgestik\n";
        }
        if (jCheckBox2.isSelected()) {
           obatDipilih += "Antasida\n";
        }
        if (jCheckBox3.isSelected()) {
            obatDipilih += "Anticemas\n";
        }
        if (jCheckBox4.isSelected()) {
            obatDipilih += "Bodrex\n";
        }
        if (jCheckBox5.isSelected()) {
            obatDipilih += "Antibiotik\n";
        }
        if (jCheckBox6.isSelected()) {
            obatDipilih += "Antikonvulsan\n";
        }
        if (jCheckBox7.isSelected()) {
            obatDipilih += "Paramex\n";
        }
        if (jCheckBox8.isSelected()) {
            obatDipilih += "Paracetamol\n";
        }
        if (jCheckBox9.isSelected()) {
            obatDipilih += "Mixagrip\n";
        }
        if (jCheckBox10.isSelected()) {
            obatDipilih += "Oskadon\n";
        }

        if (obatDipilih.equals("Obat yang Anda beli: \n")) {
            obatDipilih = "Tidak ada obat yang dipilih.";
         }
        
        obatDipilih += "\nTerima Kasih atas pembeliannya!";

         JOptionPane.showMessageDialog(null, obatDipilih);
                
        
    
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
        if (confirm == JOptionPane.YES_OPTION) {
          System.exit(0);  
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Gejala;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel daftarobat;
    private javax.swing.JPanel detailobat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
