/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;


/**
 *
 * @author ASUS
 */
public class mencoba_2 extends javax.swing.JFrame {
     private int jumlah = 0; 

    /**
     * Creates new form mencoba_2
     */
    public mencoba_2() {
        initComponents();
        txtsatu.setText(String.valueOf(jumlah));
    }
     private void showDetail(String namaObat) {
        String detail = "";
        ImageIcon icon = null;
        switch (namaObat) {
            case "Paracetamol":
                detail = "Paracetamol digunakan untuk mengurangi rasa sakit dan demam.";
                 icon = new ImageIcon(getClass().getResource("/paracetamol1.jpg"));
                break;
            case "Decolgen":
                detail = "Decolgen digunakan untuk meredakan flu dan pilek.";
                icon = new ImageIcon(getClass().getResource("/decolgen.jpeg"));
                break;
            case "Vitamin C":
                detail = "Vitamin C membantu meningkatkan daya tahan tubuh.";
                icon = new ImageIcon(getClass().getResource("/Vitamin C.jpeg"));
                break;
            case "Tetra":
                detail = "Tetra digunakan sebagai antibiotik untuk infeksi bakteri.";
                icon = new ImageIcon(getClass().getResource("/super tetra.jpeg"));
                break;
            case "Sangobion":
                detail = "Sangobion digunakan untuk mengatasi anemia.";
                icon = new ImageIcon(getClass().getResource("/sangobion.jpeg"));
                break;
            case "Antangin":
                detail = "Antangin digunakan untuk meredakan masuk angin.";
                icon = new ImageIcon(getClass().getResource("/antangin.jpeg"));
                break;
            case "Betadine":
                detail = "Betadine digunakan sebagai antiseptik untuk luka.";
                icon = new ImageIcon(getClass().getResource("/betadhine.jpeg"));
                break;
            case "Promag":
                detail = "Promag digunakan untuk mengatasi gangguan lambung.";
                icon = new ImageIcon(getClass().getResource("/gazero.jpeg"));
                break;
            case "Konidin":
                detail = "Konidin digunakan untuk meredakan batuk.";
                icon = new ImageIcon(getClass().getResource("/Konidin.png"));
                break;
            case "Paramex":
                detail = "Paramex digunakan untuk mengurangi sakit kepala.";
                icon = new ImageIcon(getClass().getResource("/paramex.jpeg"));
                break;
            default:
                detail = "Detail tidak tersedia untuk obat ini.";
        }
        javax.swing.JOptionPane.showMessageDialog(this, detail, "Informasi Obat", javax.swing.JOptionPane.INFORMATION_MESSAGE,icon);
    }
     private void showGejala(String namaObat) {
    String gejala = "";
    switch (namaObat) {
        case "Paracetamol":
            gejala = "Demam, Sakit Kepala, Nyeri Otot";
            break;
        case "Decolgen":
            gejala = "Pilek, Batuk, Demam";
            break;
        case "Vitamin C":
            gejala = "Daya Tahan Tubuh Lemah, Sariawan";
            break;
        case "Tetra":
            gejala = "Infeksi Bakteri, Radang Tenggorokan";
            break;
        case "Sangobion":
            gejala = "Anemia, Kekurangan Zat Besi";
            break;
        case "Antangin":
            gejala = "Masuk Angin, Kembung, Mual";
            break;
        case "Betadine":
            gejala = "Luka Ringan, Luka Terbuka";
            break;
        case "Promag":
            gejala = "Maag, Nyeri Lambung";
            break;
        case "Konidin":
            gejala = "Batuk Kering, Batuk Berdahak";
            break;
        case "Paramex":
            gejala = "Sakit Kepala, Demam";
            break;
        default:
            gejala = "Gejala tidak tersedia untuk obat ini.";
    }
    txt3.setText(gejala);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton6 = new javax.swing.JButton();
        arik = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        btnreset = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Betadine = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnpromag = new javax.swing.JButton();
        btnsangobion = new javax.swing.JButton();
        btntetra = new javax.swing.JButton();
        btnkonidin = new javax.swing.JButton();
        btnparamex = new javax.swing.JButton();
        btnvitimici = new javax.swing.JButton();
        btnparacetamol = new javax.swing.JButton();
        btnbetadine = new javax.swing.JButton();
        btnantangin = new javax.swing.JButton();
        btndecolgen = new javax.swing.JButton();
        rdbtnkonidin = new javax.swing.JRadioButton();
        rdbtnparamex = new javax.swing.JRadioButton();
        rdbtnsangobion = new javax.swing.JRadioButton();
        rdbtntetra = new javax.swing.JRadioButton();
        rdbtnvitiminci = new javax.swing.JRadioButton();
        rdbtnantangin = new javax.swing.JRadioButton();
        rdbtnbetadine = new javax.swing.JRadioButton();
        rdbtndecolgen = new javax.swing.JRadioButton();
        rdbtnpromag = new javax.swing.JRadioButton();
        rdbtnparacetamol = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnkurang = new javax.swing.JButton();
        txtsatu = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnreset.setText("reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel3.add(btnreset);

        btnkeluar.setText("keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel3.add(btnkeluar);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 453, 820, 40));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Paracetamol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel4.setText("Paramex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel6.setText("Sangobion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jLabel6, gridBagConstraints);

        Betadine.setText("Betadine");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(Betadine, gridBagConstraints);

        jLabel9.setText("Decolgen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Promag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Konidin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jLabel11, gridBagConstraints);

        btnpromag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gazero.jpeg"))); // NOI18N
        btnpromag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpromagActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btnpromag, gridBagConstraints);

        btnsangobion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sangobion.jpeg"))); // NOI18N
        btnsangobion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsangobionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btnsangobion, gridBagConstraints);

        btntetra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/super tetra.jpeg"))); // NOI18N
        btntetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntetraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btntetra, gridBagConstraints);

        btnkonidin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/konidin.png"))); // NOI18N
        btnkonidin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkonidinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btnkonidin, gridBagConstraints);

        btnparamex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paramex.jpeg"))); // NOI18N
        btnparamex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparamexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btnparamex, gridBagConstraints);

        btnvitimici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vitamin c.jpeg"))); // NOI18N
        btnvitimici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvitimiciActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btnvitimici, gridBagConstraints);

        btnparacetamol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paracetamol1.jpg"))); // NOI18N
        btnparacetamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparacetamolActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btnparacetamol, gridBagConstraints);

        btnbetadine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/betadhine.jpeg"))); // NOI18N
        btnbetadine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbetadineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btnbetadine, gridBagConstraints);

        btnantangin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/antangin.jpeg"))); // NOI18N
        btnantangin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnantanginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btnantangin, gridBagConstraints);

        btndecolgen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decolgen.jpeg"))); // NOI18N
        btndecolgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecolgenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(btndecolgen, gridBagConstraints);

        arik.add(rdbtnkonidin);
        rdbtnkonidin.setText("pilih");
        rdbtnkonidin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnkonidinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtnkonidin, gridBagConstraints);

        arik.add(rdbtnparamex);
        rdbtnparamex.setText("pilih");
        rdbtnparamex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnparamexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtnparamex, gridBagConstraints);

        arik.add(rdbtnsangobion);
        rdbtnsangobion.setText("pilih");
        rdbtnsangobion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnsangobionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtnsangobion, gridBagConstraints);

        arik.add(rdbtntetra);
        rdbtntetra.setText("pilih");
        rdbtntetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtntetraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtntetra, gridBagConstraints);

        arik.add(rdbtnvitiminci);
        rdbtnvitiminci.setText("pilih");
        rdbtnvitiminci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnvitiminciActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtnvitiminci, gridBagConstraints);

        arik.add(rdbtnantangin);
        rdbtnantangin.setText("pilih");
        rdbtnantangin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnantanginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtnantangin, gridBagConstraints);

        arik.add(rdbtnbetadine);
        rdbtnbetadine.setText("pilih");
        rdbtnbetadine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnbetadineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtnbetadine, gridBagConstraints);

        arik.add(rdbtndecolgen);
        rdbtndecolgen.setText("pilih");
        rdbtndecolgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtndecolgenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtndecolgen, gridBagConstraints);

        arik.add(rdbtnpromag);
        rdbtnpromag.setText("pilih");
        rdbtnpromag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnpromagActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtnpromag, gridBagConstraints);

        arik.add(rdbtnparacetamol);
        rdbtnparacetamol.setText("pilih");
        rdbtnparacetamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnparacetamolActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(rdbtnparacetamol, gridBagConstraints);

        jLabel1.setText("Antangin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel17.setText("Super Tetra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jLabel17, gridBagConstraints);

        jLabel19.setText("Vitiminci");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        jPanel1.add(jLabel19, gridBagConstraints);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 530, 353));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 100));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel23.setText("APOTEK BANG RIYYAN ");
        jPanel2.add(jLabel23);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        panel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setText("menghitung\n");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnkurang.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnkurang.setText("-");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        txtsatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsatuActionPerformed(evt);
            }
        });

        btntambah.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btntambah.setText("+");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        jLabel21.setText("obat dipilih");

        jLabel22.setText("gejala");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnkurang)
                        .addGap(12, 12, 12)
                        .addComponent(txtsatu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btntambah))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnkurang)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtsatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btntambah)))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel21))
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel22))
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 290, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsangobionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsangobionActionPerformed
        // TODO add your handling code here:
         showDetail("Sangobion");
    }//GEN-LAST:event_btnsangobionActionPerformed

    private void btnvitimiciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvitimiciActionPerformed
        // TODO add your handling code here:
        showDetail("Vitamin C");
    }//GEN-LAST:event_btnvitimiciActionPerformed

    private void btndecolgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecolgenActionPerformed
        // TODO add your handling code here:
        showDetail("Decolgen");
    }//GEN-LAST:event_btndecolgenActionPerformed

    private void btnpromagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpromagActionPerformed
        // TODO add your handling code here:
        showDetail("Promag");
    }//GEN-LAST:event_btnpromagActionPerformed

    private void btnkonidinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkonidinActionPerformed
        // TODO add your handling code here:
        showDetail("Konidin");
    }//GEN-LAST:event_btnkonidinActionPerformed

    private void rdbtnsangobionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnsangobionActionPerformed
        // TODO add your handling code here:
         txt2.setText("Sangobion");
           showGejala("Sangobion");
    }//GEN-LAST:event_rdbtnsangobionActionPerformed

    private void rdbtntetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtntetraActionPerformed
        // TODO add your handling code here:
         txt2.setText("Tetra");
           showGejala("Tetra");
    }//GEN-LAST:event_rdbtntetraActionPerformed

    private void rdbtnvitiminciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnvitiminciActionPerformed
        // TODO add your handling code here:
         txt2.setText("Vitamin C");
           showGejala("Vitamin C");
    }//GEN-LAST:event_rdbtnvitiminciActionPerformed

    private void rdbtndecolgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtndecolgenActionPerformed
        // TODO add your handling code here:
         txt2.setText("Decolgen");
           showGejala("Decolgen");
    }//GEN-LAST:event_rdbtndecolgenActionPerformed

    private void btnparacetamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparacetamolActionPerformed
        // TODO add your handling code here:
        showDetail("Paracetamol");
    }//GEN-LAST:event_btnparacetamolActionPerformed

    private void btnparamexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparamexActionPerformed
        // TODO add your handling code here:
        showDetail("Paramex");
    }//GEN-LAST:event_btnparamexActionPerformed

    private void btntetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntetraActionPerformed
        // TODO add your handling code here:
        showDetail("Tetra");
    }//GEN-LAST:event_btntetraActionPerformed

    private void btnantanginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnantanginActionPerformed
        // TODO add your handling code here:
        showDetail("Antangin");
    }//GEN-LAST:event_btnantanginActionPerformed

    private void btnbetadineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbetadineActionPerformed
        // TODO add your handling code here:
        showDetail("Betadine");
    }//GEN-LAST:event_btnbetadineActionPerformed

    private void rdbtnparacetamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnparacetamolActionPerformed
        // TODO add your handling code here:
         txt2.setText("Paracetamol");
           showGejala("Paracetamol");
    }//GEN-LAST:event_rdbtnparacetamolActionPerformed

    private void rdbtnparamexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnparamexActionPerformed
        // TODO add your handling code here:
         txt2.setText("Paramex");
           showGejala("Paramex");
    }//GEN-LAST:event_rdbtnparamexActionPerformed

    private void rdbtnantanginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnantanginActionPerformed
        // TODO add your handling code here:
         txt2.setText("Antangin");
           showGejala("Antangin");
    }//GEN-LAST:event_rdbtnantanginActionPerformed

    private void rdbtnbetadineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnbetadineActionPerformed
        // TODO add your handling code here:
         txt2.setText("Betadine");
           showGejala("Betadine");
    }//GEN-LAST:event_rdbtnbetadineActionPerformed

    private void rdbtnpromagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnpromagActionPerformed
        // TODO add your handling code here:
         txt2.setText("Promag");
           showGejala("Promag");
    }//GEN-LAST:event_rdbtnpromagActionPerformed

    private void rdbtnkonidinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnkonidinActionPerformed
        // TODO add your handling code here:
         txt2.setText("Konidin");
           showGejala("Konidin");
    }//GEN-LAST:event_rdbtnkonidinActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
           txt2.setText("");
            txt3.setText(""); 
            jumlah = 0; 
    txtsatu.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        // TODO add your handling code here:
          if (jumlah > 0) {
        jumlah--; 
        txtsatu.setText(String.valueOf(jumlah));
    } else {
        JOptionPane.showMessageDialog(this, "Jumlah tidak boleh kurang dari 0", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnkurangActionPerformed

    private void txtsatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsatuActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
         jumlah++; 
    txtsatu.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_btntambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mencoba_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mencoba_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mencoba_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mencoba_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mencoba_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Betadine;
    private javax.swing.ButtonGroup arik;
    private javax.swing.JButton btnantangin;
    private javax.swing.JButton btnbetadine;
    private javax.swing.JButton btndecolgen;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnkonidin;
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnparacetamol;
    private javax.swing.JButton btnparamex;
    private javax.swing.JButton btnpromag;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsangobion;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btntetra;
    private javax.swing.JButton btnvitimici;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton rdbtnantangin;
    private javax.swing.JRadioButton rdbtnbetadine;
    private javax.swing.JRadioButton rdbtndecolgen;
    private javax.swing.JRadioButton rdbtnkonidin;
    private javax.swing.JRadioButton rdbtnparacetamol;
    private javax.swing.JRadioButton rdbtnparamex;
    private javax.swing.JRadioButton rdbtnpromag;
    private javax.swing.JRadioButton rdbtnsangobion;
    private javax.swing.JRadioButton rdbtntetra;
    private javax.swing.JRadioButton rdbtnvitiminci;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txtsatu;
    // End of variables declaration//GEN-END:variables
}
