/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class spp extends javax.swing.JFrame {

    /**
     * Creates new form spp
     */
    public spp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bstatus = new javax.swing.JButton();
        sppbulan = new javax.swing.JTextField();
        pembayaran = new javax.swing.JTextField();
        bulanbrp = new javax.swing.JTextField();
        totspp = new javax.swing.JTextField();
        breset = new javax.swing.JButton();
        btotal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bbayar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        januari = new javax.swing.JRadioButton();
        februari = new javax.swing.JRadioButton();
        maret = new javax.swing.JRadioButton();
        april = new javax.swing.JRadioButton();
        mei = new javax.swing.JRadioButton();
        juni = new javax.swing.JRadioButton();
        juli = new javax.swing.JRadioButton();
        agustus = new javax.swing.JRadioButton();
        september = new javax.swing.JRadioButton();
        oktober = new javax.swing.JRadioButton();
        november = new javax.swing.JRadioButton();
        desember = new javax.swing.JRadioButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(554, 150));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Bulan Dibayar", "Status", "Bayar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 30)); // NOI18N
        jLabel1.setText("CLASSROOM OF THE ELITE");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\Anime_logo-removebg-preview.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("PEMBAYARAN SPP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(277, 350));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Spp Perbulan :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Total Bulan dipilih :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        bstatus.setText("Status");
        bstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstatusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(bstatus, gridBagConstraints);

        sppbulan.setEditable(false);
        sppbulan.setText("Rp.500.000");
        sppbulan.setPreferredSize(new java.awt.Dimension(100, 22));
        sppbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sppbulanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 7;
        jPanel1.add(sppbulan, gridBagConstraints);

        pembayaran.setPreferredSize(new java.awt.Dimension(100, 22));
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        jPanel1.add(pembayaran, gridBagConstraints);

        bulanbrp.setEditable(false);
        bulanbrp.setPreferredSize(new java.awt.Dimension(100, 22));
        bulanbrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanbrpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 5;
        jPanel1.add(bulanbrp, gridBagConstraints);

        totspp.setEditable(false);
        totspp.setPreferredSize(new java.awt.Dimension(100, 22));
        totspp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totsppActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        jPanel1.add(totspp, gridBagConstraints);

        breset.setText("Reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(breset, gridBagConstraints);

        btotal.setText("Total");
        btotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btotalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(btotal, gridBagConstraints);

        jLabel4.setText("Total Spp :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Pembayaran :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        bbayar.setText("Bayar");
        bbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbayarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(bbayar, gridBagConstraints);

        jLabel9.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel9, gridBagConstraints);

        jLabel10.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel10, gridBagConstraints);

        jLabel11.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel1.add(jLabel11, gridBagConstraints);

        jLabel12.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel12, gridBagConstraints);

        jLabel13.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        jPanel1.add(jLabel13, gridBagConstraints);

        jLabel14.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        jPanel1.add(jLabel14, gridBagConstraints);

        txtnama.setPreferredSize(new java.awt.Dimension(150, 30));
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(txtnama, gridBagConstraints);

        jLabel15.setText("Nama :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel15, gridBagConstraints);

        jLabel16.setText("   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jLabel16, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(277, 350));
        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 6, 6));

        januari.setText("Januari");
        januari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                januariActionPerformed(evt);
            }
        });
        jPanel2.add(januari);

        februari.setText("Februari");
        februari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                februariActionPerformed(evt);
            }
        });
        jPanel2.add(februari);

        maret.setText("Maret");
        maret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maretActionPerformed(evt);
            }
        });
        jPanel2.add(maret);

        april.setText("April");
        april.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprilActionPerformed(evt);
            }
        });
        jPanel2.add(april);

        mei.setText("Mei");
        mei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meiActionPerformed(evt);
            }
        });
        jPanel2.add(mei);

        juni.setText("Juni");
        juni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juniActionPerformed(evt);
            }
        });
        jPanel2.add(juni);

        juli.setText("Juli");
        juli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juliActionPerformed(evt);
            }
        });
        jPanel2.add(juli);

        agustus.setText("Agustus");
        agustus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agustusActionPerformed(evt);
            }
        });
        jPanel2.add(agustus);

        september.setText("September");
        september.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                septemberActionPerformed(evt);
            }
        });
        jPanel2.add(september);

        oktober.setText("Oktober");
        oktober.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oktoberActionPerformed(evt);
            }
        });
        jPanel2.add(oktober);

        november.setText("November");
        november.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novemberActionPerformed(evt);
            }
        });
        jPanel2.add(november);

        desember.setText("Desember");
        desember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desemberActionPerformed(evt);
            }
        });
        jPanel2.add(desember);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void januariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_januariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_januariActionPerformed

    private void februariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_februariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_februariActionPerformed

    private void maretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maretActionPerformed

    private void aprilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aprilActionPerformed

    private void meiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meiActionPerformed

    private void juniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juniActionPerformed

    private void juliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juliActionPerformed

    private void agustusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agustusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agustusActionPerformed

    private void septemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_septemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_septemberActionPerformed

    private void oktoberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oktoberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oktoberActionPerformed

    private void novemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novemberActionPerformed

    private void desemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desemberActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void sppbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sppbulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sppbulanActionPerformed

    private void btotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btotalActionPerformed
        // TODO add your handling code here:
        int totalPembayaran = 0;
        int hitung = 0;
        String bulanDetail = "";
        String nama = txtnama.getText();
        String totalPembayaranText = totspp.getText();

        if (januari.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "Januari";
        }
        if (februari.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "Februari";
        }
        if (maret.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "Maret";
        }
        if (april.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "April";
        }
        if (mei.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "Mei";
        }
        if (juni.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "Juni";
        }
        if (juli.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "Juli";
        }
        if (agustus.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "Agustus";
        }
        if (september.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "September";
        }
        if (oktober.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "Oktober";
        }
        if (november.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "November";
        }
        if (desember.isSelected()) {
            totalPembayaran += 500000;
            hitung++;
            bulanDetail += "Desember";
        }

        // Menghapus koma terakhir jika ada bulan yang dipilih
        if (nama.isEmpty() || bulanDetail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pastikan semua field (nama, bulan) sudah diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            totspp.setText(String.valueOf(totalPembayaran));
            bulanbrp.setText(String.valueOf(hitung));
        }
    }//GEN-LAST:event_btotalActionPerformed

    private void bulanbrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanbrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanbrpActionPerformed

    private void totsppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totsppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totsppActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembayaranActionPerformed

    private void bbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbayarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        String bulanDetail = "";
        String nama = txtnama.getText();
        String totalPembayaranText = totspp.getText();
        int bulanTerpilih = 0; // Variabel untuk menghitung jumlah bulan yang dipilih

        if (januari.isSelected()) { bulanDetail += "Januari, "; bulanTerpilih++; }
        if (februari.isSelected()) { bulanDetail += "Februari, "; bulanTerpilih++; }
        if (maret.isSelected()) { bulanDetail += "Maret, "; bulanTerpilih++; }
        if (april.isSelected()) { bulanDetail += "April, "; bulanTerpilih++; }
        if (mei.isSelected()) { bulanDetail += "Mei, "; bulanTerpilih++; }
        if (juni.isSelected()) { bulanDetail += "Juni, "; bulanTerpilih++; }
        if (juli.isSelected()) { bulanDetail += "Juli, "; bulanTerpilih++; }
        if (agustus.isSelected()) { bulanDetail += "Agustus, "; bulanTerpilih++; }
        if (september.isSelected()) { bulanDetail += "September, "; bulanTerpilih++; }
        if (oktober.isSelected()) { bulanDetail += "Oktober, "; bulanTerpilih++; }
        if (november.isSelected()) { bulanDetail += "November, "; bulanTerpilih++; }
        if (desember.isSelected()) { bulanDetail += "Desember, "; bulanTerpilih++; }

        if (!bulanDetail.isEmpty()) {
            bulanDetail = bulanDetail.substring(0, bulanDetail.length() - 2);
        }

        if (nama.isEmpty() || bulanDetail.isEmpty() || totalPembayaranText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pastikan semua field (nama, bulan, dan total pembayaran) sudah diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int totalPembayaran;
        try {
            totalPembayaran = Integer.parseInt(totalPembayaranText); // Mengubah string total pembayaran menjadi angka
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Total pembayaran harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String jumlahUangText = pembayaran.getText();
        int jumlahUang;
        try {
            jumlahUang = Integer.parseInt(jumlahUangText); // Mengubah string jumlah uang menjadi angka
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah uang yang dimasukkan harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String status = "Lunas";

        if (jumlahUang < totalPembayaran) {
            JOptionPane.showMessageDialog(this, "Jumlah uang kurang! Pembayaran gagal.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        boolean namaSama = false;
        boolean bulanSama = false;
        boolean totalSama = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            String namaDiTabel = (String) model.getValueAt(i, 0);
            String bulanDiTabel = (String) model.getValueAt(i, 1);


            if (nama.equals(namaDiTabel)) {
                namaSama = true;
                if (bulanDetail.equals(bulanDiTabel)) {
                    bulanSama = true;
                }

            }
            Object totalValue = model.getValueAt(i, 3); 
            if (totalValue != null && totalValue instanceof Integer) {
                int totalDiTabel = (Integer) totalValue;
                if (totalPembayaran == totalDiTabel) {
                    totalSama = true;
                }
            }
        }

        if (namaSama && bulanSama && totalSama) {
            JOptionPane.showMessageDialog(this, "Nama, bulan, dan total tidak boleh sama dengan data yang sudah ada!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (namaSama && !bulanSama && totalPembayaran == 0) {
            JOptionPane.showMessageDialog(this, "Silakan hitung total sebelum melanjutkan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (namaSama) {
            for (int i = 0; i < model.getRowCount(); i++) {
            String namaDiTabel = (String) model.getValueAt(i, 0);
            if (nama.equals(namaDiTabel)) {
                
                String bulanDiTabel = (String) model.getValueAt(i, 1);
                bulanDiTabel += ", " + bulanDetail; 
                model.setValueAt(bulanDiTabel, i, 1); 
                model.setValueAt(status, i, 2); 
                model.setValueAt(totalPembayaran, i, 3); 
                break;
                }
            }
        } else {
            model.addRow(new Object[]{nama, bulanDetail, status, totalPembayaran});
        }

        if (jumlahUang > totalPembayaran) {
            int kembalian = jumlahUang - totalPembayaran;
            JOptionPane.showMessageDialog(this, "Pembayaran berhasil! Kembalian: " + kembalian, "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Pembayaran berhasil! Uang pas.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bbayarActionPerformed

    private void bstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstatusActionPerformed
        // TODO add your handling code here:
        if (tabel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Silahkan Bayar Terlebih Dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }else{
            String laporan = "";

            // Pengecekan status tiap bulan
            if (januari.isSelected()) {
                laporan += "Januari: Lunas\n";
            } else {
                laporan += "Januari: Menunggak\n";
            }

            if (februari.isSelected()) {
                laporan += "Februari: Lunas\n";
            } else {
                laporan += "Februari: Menunggak\n";
            }

            if (maret.isSelected()) {
                laporan += "Maret: Lunas\n";
            } else {
                laporan += "Maret: Menunggak\n";
            }

            if (april.isSelected()) {
                laporan += "April: Lunas\n";
            } else {
                laporan += "April: Menunggak\n";
            }

            if (mei.isSelected()) {
                laporan += "Mei: Lunas\n";
            } else {
                laporan += "Mei: Menunggak\n";
            }

            if (juni.isSelected()) {
                laporan += "Juni: Lunas\n";
            } else {
                laporan += "Juni: Menunggak\n";
            }

            if (juli.isSelected()) {
                laporan += "Juli: Lunas\n";
            } else {
                laporan += "Juli: Menunggak\n";
            }

            if (agustus.isSelected()) {
                laporan += "Agustus: Lunas\n";
            } else {
                laporan += "Agustus: Menunggak\n";
            }

            if (september.isSelected()) {
                laporan += "September: Lunas\n";
            } else {
                laporan += "September: Menunggak\n";
            }

            if (oktober.isSelected()) {
                laporan += "Oktober: Lunas\n";
            } else {
                laporan += "Oktober: Menunggak\n";
            }

            if (november.isSelected()) {
                laporan += "November: Lunas\n";
            } else {
                laporan += "November: Menunggak\n";
            }

            if (desember.isSelected()) {
                laporan += "Desember: Lunas\n";
            } else {
                laporan += "Desember: Menunggak\n";
            }

            // Menampilkan status secara keseluruhan dalam satu pesan
            JOptionPane.showMessageDialog(this, "Status: " + "\n" + laporan);

            
        }                      
    }//GEN-LAST:event_bstatusActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setRowCount(0);
        }
        txtnama.setText("");
        totspp.setText("");
        pembayaran.setText("");
        bulanbrp.setText("");

        // Uncheck semua checkbox bulan
        januari.setSelected(false);
        februari.setSelected(false);
        maret.setSelected(false);
        april.setSelected(false);
        mei.setSelected(false);
        juni.setSelected(false);
        juli.setSelected(false);
        agustus.setSelected(false);
        september.setSelected(false);
        oktober.setSelected(false);
        november.setSelected(false);
        desember.setSelected(false);

    }//GEN-LAST:event_bresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agustus;
    private javax.swing.JRadioButton april;
    private javax.swing.JButton bbayar;
    private javax.swing.JButton breset;
    private javax.swing.JButton bstatus;
    private javax.swing.JButton btotal;
    private javax.swing.JTextField bulanbrp;
    private javax.swing.JRadioButton desember;
    private javax.swing.JRadioButton februari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton januari;
    private javax.swing.JRadioButton juli;
    private javax.swing.JRadioButton juni;
    private javax.swing.JRadioButton maret;
    private javax.swing.JRadioButton mei;
    private javax.swing.JRadioButton november;
    private javax.swing.JRadioButton oktober;
    private javax.swing.JTextField pembayaran;
    private javax.swing.JRadioButton september;
    private javax.swing.JTextField sppbulan;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField totspp;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
