/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
/**
 *
 * @author LUKMAN
 */
public class Praktikum2 extends javax.swing.JFrame {

    /**
     * Creates new form Praktikum2
     */
    public Praktikum2() {
        initComponents();
        setSize (760,797);
        setLocationRelativeTo(null);
            acash.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                hitungKembalian();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                hitungKembalian();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                hitungKembalian();
            }
        });
    }
    private void hitungKembalian() {
    try {
        if (!atotal.getText().isEmpty() && !acash.getText().isEmpty()) {
            double total = Double.parseDouble(atotal.getText().replace("Rp", "").trim());
            double cash = Double.parseDouble(acash.getText().trim());

            double kembali = cash - total;

            if (kembali < 0) {
                akembali.setText("Kurang");
            } else {
                akembali.setText(String.format("Rp%.0f", kembali));
            }
        } else {
            akembali.setText("");
        }
    } catch (NumberFormatException e) {
        akembali.setText("");
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        breadGroup = new javax.swing.ButtonGroup();
        toppingGroup = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rdmenu1 = new javax.swing.JRadioButton();
        rdmenu2 = new javax.swing.JRadioButton();
        rdmenu3 = new javax.swing.JRadioButton();
        rdmenu5 = new javax.swing.JRadioButton();
        rdmenu4 = new javax.swing.JRadioButton();
        rdmenu6 = new javax.swing.JRadioButton();
        rdmenu7 = new javax.swing.JRadioButton();
        rdmenu8 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtoping1 = new javax.swing.JRadioButton();
        jtoping2 = new javax.swing.JRadioButton();
        jselai1 = new javax.swing.JRadioButton();
        jselai2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ajumlah = new javax.swing.JTextField();
        jtambah = new javax.swing.JButton();
        jkurang = new javax.swing.JButton();
        atotal = new javax.swing.JTextField();
        jtotal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        acash = new javax.swing.JTextField();
        akembali = new javax.swing.JTextField();
        areset = new javax.swing.JButton();
        jtanpa = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        atanpa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField5.setText("jTextField5");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        breadGroup.add(rdmenu1);
        rdmenu1.setText("Wheat Bread-Rp23.000");

        breadGroup.add(rdmenu2);
        rdmenu2.setText("Multigrain Bread-Rp18.000");

        breadGroup.add(rdmenu3);
        rdmenu3.setText("Flat Bread-Rp14.000");

        breadGroup.add(rdmenu5);
        rdmenu5.setText("Pan Blanco-Rp45.000");

        breadGroup.add(rdmenu4);
        rdmenu4.setText("Sourdough Bread-Rp39.000");

        breadGroup.add(rdmenu6);
        rdmenu6.setText("Rye Bread-Rp17.000");

        breadGroup.add(rdmenu7);
        rdmenu7.setText("Ciabatta Bread-Rp14.000");

        breadGroup.add(rdmenu8);
        rdmenu8.setText("Challah Bread-Rp19.000");

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("TOPING DAN SELAI");

        toppingGroup.add(jtoping1);
        jtoping1.setText("Misis-Rp2.000");

        toppingGroup.add(jtoping2);
        jtoping2.setText("Marshmallow-Rp7.000");

        toppingGroup.add(jselai1);
        jselai1.setText("Selai Coklat-Rp10.000");

        toppingGroup.add(jselai2);
        jselai2.setText("Selai Anggur-Rp10.000");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("JUMLAH");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("TOTAL");

        ajumlah.setEditable(false);
        ajumlah.setText("0");
        ajumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajumlahActionPerformed(evt);
            }
        });

        jtambah.setText("TAMBAH");
        jtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtambahActionPerformed(evt);
            }
        });

        jkurang.setText("KURANG");
        jkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkurangActionPerformed(evt);
            }
        });

        atotal.setEditable(false);
        atotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atotalActionPerformed(evt);
            }
        });

        jtotal.setText("TOTAL");
        jtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("CASH");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("KEMBALI");

        acash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acashActionPerformed(evt);
            }
        });

        akembali.setEditable(false);
        akembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akembaliActionPerformed(evt);
            }
        });

        areset.setText("Reset");
        areset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aresetActionPerformed(evt);
            }
        });

        toppingGroup.add(jtanpa);
        jtanpa.setText("Tanpa Tambahan");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misis.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 255, 255)));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marshmellow.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 255, 255)));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selaianggur.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 255, 255)));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selaicoklat.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 255, 255)));

        atanpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atanpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jtoping1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jtoping2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jselai2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jselai1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(acash, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(akembali, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jtanpa)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jkurang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtambah)
                        .addGap(131, 131, 131)
                        .addComponent(jtotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atanpa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(areset)
                .addGap(139, 139, 139)
                .addComponent(jLabel9)
                .addGap(120, 120, 120))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtanpa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtoping1)
                    .addComponent(jselai1)
                    .addComponent(jtoping2)
                    .addComponent(jselai2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtotal)
                    .addComponent(atotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jkurang)
                    .addComponent(ajumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtambah)
                    .addComponent(atanpa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(areset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wheat bread.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multigrain-bread.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ciabatta bread.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pan blanco bread.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rye bread.jpg"))); // NOI18N
        jLabel18.setText("jLabel18");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/challah bread.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flat bread.jpg"))); // NOI18N
        jLabel20.setText("jLabel20");
        jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("RAJANYA ROTI HANTARAN ISTIMEWA");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sourdough bread.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 5, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdmenu1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdmenu7))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(rdmenu3))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(131, 131, 131)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rdmenu5)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(rdmenu6)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rdmenu4)
                                        .addGap(266, 266, 266))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdmenu8)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdmenu1)
                            .addComponent(rdmenu5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdmenu2)
                            .addComponent(rdmenu6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdmenu3)))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdmenu8)
                        .addComponent(rdmenu4))
                    .addComponent(rdmenu7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("TOKO BREADTOD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(211, 211, 211))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtambahActionPerformed
        // TODO add your handling code here:
    if (!(rdmenu1.isSelected() || rdmenu2.isSelected() || rdmenu3.isSelected() || 
          rdmenu4.isSelected() || rdmenu5.isSelected() || rdmenu6.isSelected() || 
          rdmenu7.isSelected() || rdmenu8.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu menu roti.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    if (!(jtoping1.isSelected() || jtoping2.isSelected() || jselai1.isSelected() || jselai2.isSelected() || jtanpa.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu topping atau 'Tanpa Topping'.", "Error", JOptionPane.ERROR_MESSAGE);
        return;  
    }

    String jumlahStr = ajumlah.getText();

    if (jumlahStr.isEmpty()) {
        ajumlah.setText("1");  
    } else {
        int jumlah = Integer.parseInt(jumlahStr); 
        jumlah++;  
        ajumlah.setText(String.valueOf(jumlah)); 
    }
    hitungKembalian();
    }//GEN-LAST:event_jtambahActionPerformed

    private void jkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkurangActionPerformed
        // TODO add your handling code here:
    if (!(rdmenu1.isSelected() || rdmenu2.isSelected() || rdmenu3.isSelected() || 
          rdmenu4.isSelected() || rdmenu5.isSelected() || rdmenu6.isSelected() || 
          rdmenu7.isSelected() || rdmenu8.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu menu roti.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    if (!(jtoping1.isSelected() || jtoping2.isSelected() || jselai1.isSelected() || jselai2.isSelected() || jtanpa.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu topping atau 'Tanpa Topping'.", "Error", JOptionPane.ERROR_MESSAGE);
        return;  
    }

    String jumlahStr = ajumlah.getText();

    if (jumlahStr.isEmpty()) {
        ajumlah.setText("0");  
    } else {
        int jumlah = Integer.parseInt(jumlahStr); 
        if (jumlah > 0) {  
            jumlah--;  
        }
        ajumlah.setText(String.valueOf(jumlah)); 
    }
    hitungKembalian();
    }//GEN-LAST:event_jkurangActionPerformed

    private void ajumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajumlahActionPerformed
        ajumlah.setText("1");  
    }//GEN-LAST:event_ajumlahActionPerformed

    private void jtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotalActionPerformed
    double hargaRoti = 0, hargaTopping = 0;

    String jumlahStr = ajumlah.getText().trim();
    if (jumlahStr.isEmpty() || jumlahStr.equals("0")) {
        JOptionPane.showMessageDialog(this, "Tambahkan dulu jumlahnya.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    int jumlah = Integer.parseInt(jumlahStr);

    if (!(rdmenu1.isSelected() || rdmenu2.isSelected() || rdmenu3.isSelected() || 
          rdmenu4.isSelected() || rdmenu5.isSelected() || rdmenu6.isSelected() || 
          rdmenu7.isSelected() || rdmenu8.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu menu roti.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    if (!(jtoping1.isSelected() || jtoping2.isSelected() || jselai1.isSelected() || jselai2.isSelected() || jtanpa.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu topping atau 'Tanpa Topping'.", "Error", JOptionPane.ERROR_MESSAGE);
        return;  
    }

    if (rdmenu1.isSelected()) {
        hargaRoti = 23000;
    } else if (rdmenu2.isSelected()) {
        hargaRoti = 18000;
    } else if (rdmenu3.isSelected()) {
        hargaRoti = 14000;
    } else if (rdmenu4.isSelected()) {
        hargaRoti = 39000;
    } else if (rdmenu5.isSelected()) {
        hargaRoti = 45000;
    } else if (rdmenu6.isSelected()) {
        hargaRoti = 17000;
    } else if (rdmenu7.isSelected()) {
        hargaRoti = 20000;
    } else if (rdmenu8.isSelected()) {
        hargaRoti = 25000;
    }

    if (jtoping1.isSelected()) {
        hargaTopping = 2000;
    } else if (jtoping2.isSelected()) {
        hargaTopping = 7000;
    } else if (jselai1.isSelected()) {
        hargaTopping = 10000;
    } else if (jselai2.isSelected()) {
        hargaTopping = 10000;
    } else if (jtanpa.isSelected()) {
        hargaTopping = 0;  
    }

    double totalTanpaDiskon = (hargaRoti + hargaTopping) * jumlah;

    double totalDenganDiskon = totalTanpaDiskon;
    if (totalTanpaDiskon > 100000) {
        totalDenganDiskon = totalTanpaDiskon * 0.95;
    }
    
    if (totalTanpaDiskon > 100000) {
        atanpa.setText(String.format("Rp%.0f", totalTanpaDiskon));
    } 
    else {
        atanpa.setText("Belum dapat diskon");
    }

    atotal.setText(String.format("Rp%.0f", totalDenganDiskon));
    hitungKembalian();
    }//GEN-LAST:event_jtotalActionPerformed

    private void atotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atotalActionPerformed
        // TODO add your handling code here:
    double hargaRoti = 0, hargaTopping = 0;
    int jumlah = Integer.parseInt(ajumlah.getText());

    if (!(rdmenu1.isSelected() || rdmenu2.isSelected() || rdmenu3.isSelected() || 
          rdmenu4.isSelected() || rdmenu5.isSelected() || rdmenu6.isSelected() || 
          rdmenu7.isSelected() || rdmenu8.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu menu roti.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    if (!(jtoping1.isSelected() || jtoping2.isSelected() || jselai1.isSelected() || jselai2.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu topping.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    }//GEN-LAST:event_atotalActionPerformed

    private void acashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acashActionPerformed
        // TODO add your handling code here:
    hitungKembalian();
    }//GEN-LAST:event_acashActionPerformed

    private void akembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akembaliActionPerformed

    private void aresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aresetActionPerformed
        // TODO add your handling code here:
        ajumlah.setText("");
        atotal.setText("");
        atanpa.setText("");
        acash.setText("");
        akembali.setText("");
        breadGroup.clearSelection();
        toppingGroup.clearSelection();

        if (!atotal.getText().isEmpty() && !acash.getText().isEmpty()) {
            double total = Double.parseDouble(atotal.getText().replace("Rp", "").trim());
            double cash = Double.parseDouble(acash.getText().trim());

            double kembali = cash - total;
            akembali.setText(String.format("Rp%.0f", kembali));
        }
    }//GEN-LAST:event_aresetActionPerformed

    private void atanpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atanpaActionPerformed
        // TODO add your handling code here:
    double hargaRoti = 0, hargaTopping = 0;
    int jumlah = Integer.parseInt(ajumlah.getText().trim());

    if (!(rdmenu1.isSelected() || rdmenu2.isSelected() || rdmenu3.isSelected() || 
          rdmenu4.isSelected() || rdmenu5.isSelected() || rdmenu6.isSelected() || 
          rdmenu7.isSelected() || rdmenu8.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu menu roti.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    if (!(jtoping1.isSelected() || jtoping2.isSelected() || jselai1.isSelected() || jselai2.isSelected() || jtanpa.isSelected())) {
        JOptionPane.showMessageDialog(this, "Silakan pilih salah satu topping.", "Error", JOptionPane.ERROR_MESSAGE);
        return;  
    }
    double totalAsli = (hargaRoti + hargaTopping) * jumlah;

    atotal.setText(String.format("Rp%.0f", totalAsli));
    }//GEN-LAST:event_atanpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acash;
    private javax.swing.JTextField ajumlah;
    private javax.swing.JTextField akembali;
    private javax.swing.JButton areset;
    private javax.swing.JTextField atanpa;
    private javax.swing.JTextField atotal;
    private javax.swing.ButtonGroup breadGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton jkurang;
    private javax.swing.JRadioButton jselai1;
    private javax.swing.JRadioButton jselai2;
    private javax.swing.JButton jtambah;
    private javax.swing.JRadioButton jtanpa;
    private javax.swing.JRadioButton jtoping1;
    private javax.swing.JRadioButton jtoping2;
    private javax.swing.JButton jtotal;
    private javax.swing.JRadioButton rdmenu1;
    private javax.swing.JRadioButton rdmenu2;
    private javax.swing.JRadioButton rdmenu3;
    private javax.swing.JRadioButton rdmenu4;
    private javax.swing.JRadioButton rdmenu5;
    private javax.swing.JRadioButton rdmenu6;
    private javax.swing.JRadioButton rdmenu7;
    private javax.swing.JRadioButton rdmenu8;
    private javax.swing.ButtonGroup toppingGroup;
    // End of variables declaration//GEN-END:variables
}
